spring:
  datasource:
    name: dev
    url: jdbc:mysql://175.27.166.44:8306/alpha
    username: root
    password: wonderland
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      host: 175.27.166.44
      port: 8379
      password: wonderland
      jedis:
        pool:
          max-active: 32
          max-wait: 16
          min-idle: 8

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.clawchat.alpha.entity



